# -*- coding: utf-8 -*-
"""Desafio 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13QaWmF1JWfoCfg2DimtpA8-J68JJiebQ
"""

vacinas = ["Astrazeneca", "Pfizer", "Sinovac", "Janssen"]
eficacia = ["62%", "94%", "70%", "56%" ]
uso_emergencial = "Aprovado", "Negado", "Recusado"
dados_list = [("Astrazeneca", "Eficácia de 62% e uso emergencial aprovado"), 
              ("Pfizer", "Eficácia de 94% e uso emergencial aprovado"), 
              ("Sinovac", "Eficácia de 70% e uso emergencial aprovado"), 
              ("Janssen", "Eficácia de 56% e uso emergencial aprovado")]

#Frase com as listas
print("As vacinas que estão em análise são: ", vacinas, 
      "com suas eficácias: ", eficacia,
      ", podendo ter o uso emergencial ", uso_emergencial)

#Associando as listas
for i in range(0,4):
  print(vacinas[i])
  print(eficacia[i])

#Organizando a lista em ordem alfabética
sorted(vacinas)

#Inserindo item na lista
nome = input("Digite o nome de uma vacina: ")
vacinas.append(nome)
print(vacinas)

#Criando um diconário aparti de uma lista
dados_vacinas = dict(dados_list)
print(dados_vacinas)

#Encontrando dados no dicionário
nomes = input("Qual vacina deseja encontrar? ")
print(dados_vacinas[nomes])

